name: Create and publish a Docker image

on:
  push:
    branches:
    - 'main'
    - 'release/v1.*'

    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-manager:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "[kubelb-manager] Extract metadata (tags, labels) for Docker"
        id: docker_meta_manager
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-manager
          tags: |
            type=semver,pattern={{version}},enable=true
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=v1.1-latest,enable=${{ github.ref == format('refs/heads/{0}', 'release/v1.1') }}
            type=raw,value=v1.2-latest,enable=${{ github.ref == format('refs/heads/{0}', 'release/v1.2') }}

      - name: "[kubelb-manager] Build and push Docker image"
        uses: docker/build-push-action@v6
        id: build_push_manager
        with:
          context: .
          file: kubelb.dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.docker_meta_manager.outputs.tags }}
          labels: ${{ steps.docker_meta_manager.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "[kubelb-manager] Sign the published Docker image"
        id: sign_manager
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.docker_meta_manager.outputs.tags }}
          DIGEST: ${{ steps.build_push_manager.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  build-push-ccm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "[kubelb-ccm] Extract metadata (tags, labels) for Docker"
        id: docker_meta_ccm
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ccm
          tags: |
            type=semver,pattern={{version}},enable=true
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=v1.1-latest,enable=${{ github.ref == format('refs/heads/{0}', 'release/v1.1') }}
            type=raw,value=v1.2-latest,enable=${{ github.ref == format('refs/heads/{0}', 'release/v1.2') }}

      - name: "[kubelb-ccm] Build and push Docker image"
        uses: docker/build-push-action@v6
        id: build_push_ccm
        with:
          context: .
          file: ccm.dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.docker_meta_ccm.outputs.tags }}
          labels: ${{ steps.docker_meta_ccm.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "[kubelb-ccm] Sign the published Docker image"
        id: sign_ccm
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.docker_meta_ccm.outputs.tags }}
          DIGEST: ${{ steps.build_push_ccm.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
